version: '3'

services:

  ihris:
    build:
      context: .
      dockerfile: ./Dockerfile-manage-demo
    ports:
      - "80:80"
    links:
      - mysql:mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "manage"
      MYSQL_DATABASE: "manage"
      MYSQL_USER: "manage"
      MYSQL_PASSWORD: "manage"
